# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userprofile_created_recipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2015, 12, 9, 19, 30, 31, 151387, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recipecomment',
            unique_together=set([('user', 'recipe')]),
        ),
    ]
